# Configuration for the nginx web server

limit_req_zone $binary_remote_addr zone=mylimit:5m rate=60r/s;
server {
    server_name theriddleman.com www.theriddleman.com;

    location / {
        limit_req zone=mylimit burst=30 nodelay;
        limit_req_status 427;
        proxy_pass http://127.0.0.1:3000;
    }

    location /be/ {
        limit_req zone=mylimit burst=30 nodelay;
        limit_req_status 427;                                                                                        
        proxy_pass http://unix:/run/gunicorn.sock;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
    }                                                                                                                
    location /static/ {
        autoindex on;
        autoindex_exact_size off;
        root /var/www/dkriddles;
    }

    location = /favicon.ico {
        access_log off;
        proxy_pass http://127.0.0.1:3000/favicon.ico;
    }                                                                                                                
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/theriddleman.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/theriddleman.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host ~ ^(theriddleman\.com|www\.theriddleman\.com)$) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen       80;
    listen       [::]:80;
    server_name  theriddleman.com www.theriddleman.com;
    return 404; # managed by Certbot
}