# Generated by Django 5.2.13 on 2026-09-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
